/**
 * Changelog Entries Data
 */

export const CHANGELOG_ENTRIES = [
  {
    version: '1.0.26',
    date: '2026-01-18',
    type: 'patch',
    title: 'Documentation Consolidation',
    highlights: [
      'Merged STABILITY-ROADMAP.md into CHANGELOG.md',
      'Cleaned up redundant documentation files',
      'Archived outdated roadmaps and plans',
      'Streamlined root-level markdown files',
    ],
    features: [
      { title: 'Stability Roadmap Merge', description: 'Complete stability roadmap summary now in CHANGELOG.md under "Stability Roadmap (Complete)" section.' },
      { title: 'File Cleanup', description: 'Removed STABILITY-ROADMAP.md, UPGRADE_PALN.md, and docs/STABILITY_ROADMAP.md (duplicates/obsolete).' },
      { title: 'Documentation Archive', description: 'Moved ROADMAP.md and BUNDLE_OPTIMIZATION_PLAN.md to docs/archive/ for historical reference.' },
      { title: 'Standardized Root Files', description: 'Root now contains only standard files: README, CHANGELOG, CLAUDE, INSTALL, ENTERPRISE_ROADMAP, and OSS standards.' },
    ],
  },
  {
    version: '1.0.25',
    date: '2026-01-18',
    type: 'patch',
    title: 'Documentation Alignment & Roadmap Updates',
    highlights: [
      'Comprehensive documentation review and alignment',
      'ENTERPRISE_ROADMAP.md updated with implementation status',
      'README.md updated to reflect current features',
      'All roadmaps now accurately reflect project state',
    ],
    features: [
      { title: 'ENTERPRISE_ROADMAP Updates', description: 'Updated to show Phases 1, 2, 3, 5 complete. RBAC, quotas, API keys, and agent observability all implemented.' },
      { title: 'README.md Updates', description: 'Updated version to v1.0.24, test counts (~2,000 tests), architecture diagram, and added enterprise features section.' },
      { title: 'Documentation Accuracy', description: 'All roadmap documents now accurately reflect the current implementation status of the project.' },
      { title: 'Enterprise Features Documented', description: 'Added section documenting RBAC, resource quotas, API key authentication, and audit logging.' },
    ],
  },
  {
    version: '1.0.24',
    date: '2026-01-18',
    type: 'major',
    title: '100% Backend Route Test Coverage',
    highlights: [
      'Complete backend route test coverage (44/44 routes)',
      '~950 backend route tests total',
      'All API endpoints now have comprehensive tests',
      'Test infrastructure fully mature',
    ],
    features: [
      { title: 'Aider Tests', description: '36 tests for Aider AI integration including sessions, models, commands, and output streaming' },
      { title: 'Claude Flow Tests', description: '28 tests for multi-agent swarm management, templates, roles, and quick tasks' },
      { title: 'Tabby Tests', description: '21 tests for Tabby Docker container management and IDE integration' },
      { title: 'Audit Tests', description: '20 tests for admin audit log access with filtering, stats, export, and purge' },
      { title: 'Lifecycle Tests', description: '25 tests for lifecycle agent scanning, tools status, and queue management' },
      { title: 'Project Tags Tests', description: '23 tests for project tag management and categorization' },
      { title: 'Checkpoints Tests', description: '17 tests for git checkpoint system with restore and snapshot operations' },
      { title: 'Browser Tests', description: '25 tests for file browser with path security and directory traversal protection' },
      { title: 'Files Tests', description: '14 tests for file operations, logs, diff viewer, export, and import' },
      { title: 'System Tests', description: '10 tests for system updates, version checking, and changelog endpoints' },
      { title: 'Project Templates Tests', description: '18 tests for template listing, project creation, migration, and compliance' },
    ],
  },
  {
    version: '1.0.23',
    date: '2026-01-18',
    type: 'patch',
    title: 'Hook Tests & ESLint Fixes',
    highlights: [
      'Added 190+ hook tests for remaining hooks',
      'Fixed all ESLint errors (59 resolved)',
      'Improved test isolation and React Testing Library patterns',
    ],
    features: [
      { title: 'useAgentSocket Tests', description: '18 tests covering Socket.IO agent status, output streaming, and running agent tracking' },
      { title: 'useAiderVoice Tests', description: '25 tests for Aider voice integration, session management, and command routing' },
      { title: 'useVoiceRecognition Tests', description: 'Tests for Web Speech API integration with mock SpeechRecognition' },
      { title: 'useVoiceActivityDetection Tests', description: 'Tests for VAD hook with Web Audio API mocking' },
      { title: 'useVoiceFeedback Tests', description: 'Tests for audio feedback utilities and voiceSounds exports' },
      { title: 'ESLint Error Fixes', description: 'Resolved 59 ESLint errors including undefined variables, useless escapes, empty catches, and hook violations' },
    ],
  },
  {
    version: '1.0.22',
    date: '2026-01-18',
    type: 'major',
    title: 'Resource Quotas & API Keys',
    highlights: [
      'Resource quota system with role-based limits',
      'API key authentication for programmatic access',
      'Per-user rate limiting with sliding window',
      'Quota enforcement on resource creation',
    ],
    features: [
      { title: 'ResourceQuota Model', description: 'Per-user and per-role quotas for sessions, agents, prompts, snippets, and folders with configurable limits' },
      { title: 'API Key Authentication', description: 'Generate API keys with SHA-256 hashing, scopes (read/write/agents/admin), IP whitelisting, and expiration' },
      { title: 'Quota Enforcement Middleware', description: 'enforceQuota() middleware applied to agent, session, prompt, snippet, and folder creation routes' },
      { title: 'Per-User Rate Limiting', description: 'Sliding window rate limiting with in-memory cache and database persistence, respects user quota settings' },
      { title: 'Quota Management API', description: 'Admin endpoints for viewing/setting user quotas, role defaults, and API key management' },
      { title: 'Role-Based Default Quotas', description: 'SUPER_ADMIN (100 sessions), ADMIN (20), USER (5), VIEWER (read-only) with customizable overrides' },
    ],
  },
  {
    version: '1.0.21',
    date: '2026-01-18',
    type: 'major',
    title: 'RBAC & Agent Observability',
    highlights: [
      'Role-based access control (RBAC) with 4-tier hierarchy',
      'Agent observability widget with real-time Socket.IO updates',
      'Agent detail drawer with live output streaming',
      'Frontend permission gates and role-based UI',
    ],
    features: [
      { title: 'RBAC Middleware', description: 'Server-side role enforcement with SUPER_ADMIN > ADMIN > USER > VIEWER hierarchy and ownership-based data isolation' },
      { title: 'useAuth RBAC Hooks', description: 'hasRole(), canAccess(), isOwner(), canAccessResource() utilities for frontend permission checks' },
      { title: 'PermissionGate Component', description: 'Declarative component for conditionally rendering UI based on user roles' },
      { title: 'Role-Based Tab Visibility', description: 'AdminDashboard tabs filtered by role - Server and Security tabs require ADMIN+' },
      { title: 'AgentsWidget', description: 'Real-time agent status widget showing running agents, all agents, and execution history with run/stop controls' },
      { title: 'useAgentSocket Hook', description: 'Socket.IO integration for live agent:status and agent:output events with running state tracking' },
      { title: 'AgentDetailDrawer', description: 'Slide-out drawer with Overview, Output, and History tabs for detailed agent inspection and live output streaming' },
      { title: 'Database RBAC Fields', description: 'Added ownerId to Session, Prompt, Snippet, Agent models for ownership-based filtering' },
    ],
  },
  {
    version: '1.0.20',
    date: '2026-01-18',
    type: 'major',
    title: 'Enterprise Mission Control Roadmap',
    highlights: [
      'Enterprise upgrade roadmap with RBAC architecture',
      'Multi-user role hierarchy design (SUPER_ADMIN/ADMIN/USER/VIEWER)',
      'Mission Control three-pane layout specification',
      'Agent observability drawer architecture',
    ],
    features: [
      { title: 'ENTERPRISE_ROADMAP.md', description: 'Comprehensive enterprise upgrade plan with current state analysis, RBAC implementation strategy, and prioritization matrix' },
      { title: 'Security Gap Analysis', description: 'Identified 350+ unprotected API endpoints and critical admin routes without authorization checks' },
      { title: 'RBAC Design', description: 'Full role hierarchy with permission matrix for sessions, projects, infrastructure, agents, and collaboration features' },
      { title: 'Database Schema Plan', description: 'User, Team, ProjectAssignment, and AuditLog models designed for multi-tenancy support' },
      { title: 'Phase Implementation Plan', description: '5-phase roadmap: Security Foundation, Data Isolation, Mission Control UI, Audit & Teams, Polish & Quotas' },
    ],
  },
  {
    version: '1.0.19',
    date: '2026-01-18',
    type: 'minor',
    title: 'Terminal Unicode Fix & Test Coverage Expansion',
    highlights: [
      'Fixed Claude CLI logo rendering in terminal (Unicode11 addon)',
      '154 new tests added for component coverage',
      '7 new test files for core components',
      'Test coverage increased to 20%+ functions',
    ],
    features: [
      { title: 'Unicode11 Terminal Fix', description: 'Added @xterm/addon-unicode11 for proper character width calculation, fixing Claude CLI logo block drawing characters' },
      { title: 'BulkActionBar Tests', description: '30 tests covering multi-select session operations, folder/tag menus, and delete confirmations' },
      { title: 'SessionManager Tests', description: '22 tests for session widget including kill all, duration formatting, and confirm states' },
      { title: 'TemplateCard Tests', description: '24 tests for project template cards including difficulty badges and tech stack display' },
      { title: 'CommandPalette Tests', description: '31 tests for fuzzy search, keyboard navigation, and command execution' },
      { title: 'Sidebar Tests', description: '27 tests for LeftSidebar and RightSidebar components including widget rendering' },
      { title: 'AiderModeToggle Tests', description: '20 tests for mode switching between Claude Code and Aider' },
    ],
  },
  {
    version: '1.0.18',
    date: '2026-01-17',
    type: 'major',
    title: 'Phase 5.4 Complete - Nonce-Based CSP & Zod Validation',
    highlights: [
      'Nonce-based Content Security Policy replaces unsafe-inline',
      '25+ API methods wrapped with Zod response validation',
      'Test infrastructure updated for centralized API mocking',
      'Security headers dynamically generated per-request',
    ],
    features: [
      { title: 'Nonce-Based CSP', description: 'Cryptographic nonces generated per-request using crypto.randomBytes(16), injected into style tags and meta tag for frontend access' },
      { title: 'CSP Header Updates', description: 'Removed unsafe-inline from script-src and style-src, replaced with nonce-{value} directives while keeping unsafe-eval for xterm.js WebGL' },
      { title: 'Zod Response Validation', description: '25+ API methods wrapped with validated() function providing non-breaking schema validation with console warnings' },
      { title: 'API Validation Coverage', description: 'systemApi, dockerApi, infraApi, firewallApi, sessionsApi, foldersApi, tagsApi, promptsApi, snippetsApi, agentsApi, gitApi, and more validated' },
      { title: 'Test Mocking Updates', description: 'TokenUsageWidget and other tests updated to mock centralized aiApi instead of global.fetch' },
      { title: 'Security Middleware Refactor', description: 'securityHeaders converted to function returning helmet middleware with dynamic nonce support' },
    ],
  },
  {
    version: '1.0.17',
    date: '2026-01-17',
    type: 'major',
    title: 'Phase 5.1 Complete - Full API Service Migration',
    highlights: [
      'All 70+ components migrated to centralized API service',
      '35+ domain-specific API modules in api.js',
      'Zero direct fetch() calls remaining in components',
      'Ready for Phase 5.2 Zod Response Validation',
    ],
    features: [
      { title: 'Final Batch Migration', description: 'App.jsx, DiffViewer, ContextPanel, ResourceChart, ScheduleManager, AgentExecutionLog, SettingsPanel, VoiceCommandPanel, ProjectContextMenu, GitHubProjectPanel all migrated' },
      { title: 'New API Modules', description: 'Added diffApi, notesApi, sessionsPersistedApi, metricsApi, projectContextsApi, scheduledTasksApi, agentExecutionsApi, voiceApi, projectContextApi, githubProjectsApi' },
      { title: 'App.jsx Cleanup', description: 'Main app component now uses projectsApi, systemApi, notesApi, sessionsPersistedApi for all data fetching' },
      { title: 'Consistent Error Handling', description: 'All components use ApiError.getUserMessage() for user-friendly error messages' },
      { title: 'Intentional Exceptions', description: 'useAuth.jsx (/auth/me) and OfflineMode.jsx (generic sync) remain as direct fetch by design' },
    ],
  },
  {
    version: '1.0.16',
    date: '2026-01-17',
    type: 'major',
    title: 'Phase 5.1 - Centralized API Service Migration',
    highlights: [
      'Migrated 68+ fetch() calls to centralized API service',
      '8 new domain-specific API modules with error handling',
      'X-Request-ID tracing and Sentry integration on all API calls',
      'ApiError class with user-friendly error messages',
    ],
    features: [
      { title: 'API Service Architecture', description: 'Centralized api.js with consistent error handling, request tracing, retry logic, and cancellation support' },
      { title: 'Domain APIs', description: 'New authentikApi, serverApi, infraExtendedApi, stackApi, serverUsersApi, firewallExtendedApi, adminApi, and aiApi modules' },
      { title: 'Hooks Migration', description: 'useSessionManagement and useAiderVoice migrated from direct fetch() to centralized API with 21 calls updated' },
      { title: 'Admin Tab Migration', description: '11 admin tab components migrated: Authentik, Logs, Network, Packages, Processes, Stack, Users, Firewall, Fail2ban, History, Scheduled' },
      { title: 'Widget Migration', description: 'DockerWidget and TokenUsageWidget now use centralized dockerApi and aiApi services' },
      { title: 'Error Handling', description: 'All migrated components use ApiError.getUserMessage() for user-friendly error display' },
    ],
  },
  {
    version: '1.0.15',
    date: '2026-01-17',
    type: 'major',
    title: 'Phase 4 Observability Complete',
    highlights: [
      'Database connection pool metrics for Prometheus',
      'Socket.IO error tracking with Sentry breadcrumbs',
      'X-Request-ID propagation through frontend API layer',
      '5 new Prometheus alert rules for pool exhaustion and Socket.IO',
    ],
    features: [
      { title: 'Pool Metrics', description: 'New consoleweb_db_pool_size, db_pool_idle, db_pool_waiting, and db_pool_exhausted metrics with 5-second collection interval' },
      { title: 'Socket.IO Sentry', description: 'Error handlers, breadcrumbs for connect/disconnect/select-project, and server-level connection_error tracking' },
      { title: 'API Request Tracing', description: 'X-Request-ID headers in all API requests, breadcrumbs for HTTP calls, and Sentry capture for 5xx errors with request IDs' },
      { title: 'Alert Rules', description: 'Critical P95 >2s latency, database pool exhaustion, pool near-exhaustion warning, Socket.IO disconnect rate, and connection churn alerts' },
    ],
  },
  {
    version: '1.0.14',
    date: '2026-01-17',
    type: 'major',
    title: 'Phase 3 Testing Foundation Complete',
    highlights: [
      'Storybook 10.1 with 4 component stories for visual testing',
      'Playwright E2E tests: 36 tests across terminal, projects, server, security',
      'Unit test coverage: hooks 32.93%, services 90.1%',
      'New tests: useTheme, useKeyboardShortcuts, api.js service',
    ],
    features: [
      { title: 'Storybook Setup', description: 'Storybook 10.1.11 with Tailwind CSS, dark theme preset, and component stories for TabButton, SubTabBar, TabContainer, ErrorBoundary' },
      { title: 'E2E Test Suite', description: '36 Playwright tests covering terminal sessions, project management, Docker controls, and security features across Chromium and Firefox' },
      { title: 'useTheme Tests', description: '17 tests covering theme persistence, cycling, validation, and DOM application' },
      { title: 'useKeyboardShortcuts Tests', description: '27 tests covering shortcut parsing, handler execution, input element handling, and modifier keys' },
      { title: 'API Service Tests', description: '33 tests for ApiError class, HTTP methods, request cancellation, and domain-specific APIs' },
      { title: 'Coverage Targets Met', description: 'src/hooks achieved 32.93% coverage (target: 30%), src/services achieved 90.1% coverage' },
    ],
  },
  {
    version: '1.0.13',
    date: '2026-01-17',
    type: 'major',
    title: 'Stability Hardening - Phase 1 Complete',
    highlights: [
      'Error handling standardized across 300+ catch blocks in 24 route files',
      'Frontend components now show error states with retry buttons',
      'Error Boundaries wrap all critical UI components',
      'Silent failures eliminated with debug logging',
    ],
    features: [
      { title: 'sendSafeError Pattern', description: 'All 24 route files updated with sendSafeError() for consistent error responses and logging' },
      { title: 'Frontend Error States', description: '6 components (ProjectsTab, OverviewPane, DockerPane, AiderSessionPanel, DatabaseBrowser, GitWorkflow) now show error UI with retry' },
      { title: 'Error Boundaries', description: 'Terminal, LeftSidebar, RightSidebar, HomeDashboard, and all widgets wrapped in ErrorBoundary' },
      { title: 'Silent Catch Fixes', description: 'infrastructure.js silent catches converted to debug-logged best-effort operations' },
      { title: 'Test Fixes', description: 'agentSchema tests fixed - all 148 backend tests passing' },
      { title: 'Stability Roadmap', description: 'STABILITY-ROADMAP.md created for tracking 5-phase hardening effort' },
    ],
  },
  {
    version: '1.0.12',
    date: '2026-01-17',
    type: 'patch',
    title: 'Component Modularization Complete',
    highlights: [
      'All large components now use modular directory structure',
      'Extracted reusable sub-components and constants',
      'Improved code maintainability and navigation',
      'Consistent barrel export patterns across modules',
    ],
    features: [
      { title: 'Memory Bank Module', description: 'MemoryCard component with MEMORY_TYPES and SCOPE_COLORS constants extracted' },
      { title: 'Prompt Library Module', description: 'PromptCard, PromptEditor, VariableInput components with extractVariables utility' },
      { title: 'Create Project Module', description: 'StepIndicator, Toggle, InputField, TemplateCard, SummaryItem with TEMPLATES and STEPS constants' },
      { title: 'Voice Command Module', description: 'VoiceSettingsPanel, VoiceHistoryPanel, AudioVisualization, CommandConfirmation components' },
      { title: 'About Module', description: 'StatCard, CapabilityCard, DevToolCard with comprehensive feature constants' },
      { title: 'MCP Server Module', description: 'Transport labels and icons with modular directory structure' },
    ],
  },
  {
    version: '1.0.11',
    date: '2026-01-17',
    type: 'major',
    title: 'Bundle Optimization & Component Refactoring',
    highlights: [
      'Reduced initial bundle size by 87% (1,792KB → 226KB)',
      'Implemented React.lazy() code-splitting for 20+ components',
      'Created modular settings pane components architecture',
      'Fixed Tailwind safelist warning on production builds',
    ],
    features: [
      { title: 'Vendor Chunk Splitting', description: 'Separate chunks for React, Socket.IO, xterm, Sentry, and markdown with optimal caching' },
      { title: 'Lazy-Loaded Modals', description: '20+ modal and admin components now load on-demand, reducing initial page load' },
      { title: 'Settings Module', description: 'New src/components/settings/ directory with GeneralPane, AppearancePane, ShortcutsPane, PersonasPane components' },
      { title: 'Build Optimization', description: 'Vite manualChunks config for intelligent bundle splitting and caching' },
      { title: 'Tailwind Cleanup', description: 'Removed broken safelist pattern that caused build warnings' },
      { title: 'App.jsx Refactor', description: 'Converted 20+ static imports to React.lazy() for dynamic loading' },
    ],
  },
  {
    version: '1.0.10',
    date: '2026-01-17',
    type: 'minor',
    title: 'Infrastructure Reliability & Version Sync',
    highlights: [
      'Robust auto-start scripts for sovereign-stack services',
      'Fixed version display consistency across all UI components',
      'Improved Docker container state handling after reboot',
      'Enhanced system boot reliability for auth and proxy services',
    ],
    features: [
      { title: 'Startup Scripts', description: 'New startup.sh with Docker cleanup, health checks, and graceful recovery for sovereign-stack' },
      { title: 'Shutdown Scripts', description: 'Graceful shutdown.sh with proper timeout handling for container orchestration' },
      { title: 'Status Monitoring', description: 'New status.sh script for quick health checks of all services and ports' },
      { title: 'Systemd Service', description: 'Updated sovereign-stack.service with robust error handling and restart policies' },
      { title: 'Version Consistency', description: 'Synchronized version display in header, footer, About modal, and changelog' },
      { title: 'Boot Recovery', description: 'Automatic cleanup of orphaned Docker containers and corrupted state on startup' },
    ],
  },
  {
    version: '1.0.9',
    date: '2026-01-17',
    type: 'major',
    title: 'Full Observability Stack',
    highlights: [
      'OpenTelemetry distributed tracing with Jaeger integration',
      'Loki log aggregation with Promtail collectors',
      'Grafana dashboard and AlertManager rules for Prometheus',
      'Complete production observability infrastructure',
    ],
    features: [
      { title: 'Distributed Tracing', description: 'OpenTelemetry auto-instrumentation for HTTP, Express, PostgreSQL with Jaeger export' },
      { title: 'Log Aggregation', description: 'Structured JSON logs collected by Promtail and shipped to Loki for centralized querying' },
      { title: 'Grafana Dashboard', description: '9 pre-built panels: request rate, p95 latency, error rate, WebSocket connections, memory usage' },
      { title: 'AlertManager Rules', description: '9 production alerts: high error rate, slow queries, service down, memory warnings' },
      { title: 'Docker Stack', description: 'One-command deployment of Jaeger, Loki, and Promtail via docker compose' },
      { title: 'Trace Context', description: 'X-Trace-Id header in responses for request correlation across services' },
    ],
  },
  {
    version: '1.0.8',
    date: '2026-01-17',
    type: 'major',
    title: 'Production Hardening & Validation',
    highlights: [
      'Zod validation schemas applied across all 41+ route files',
      'Error sanitization with sendSafeError() prevents information leakage',
      'Sentry error tracking integration for production monitoring',
      'Connection draining for graceful shutdown during deployments',
    ],
    features: [
      { title: 'Input Validation', description: 'All API routes now use Zod schemas via validateBody() middleware for strict input validation' },
      { title: 'Error Sanitization', description: 'sendSafeError() returns sanitized messages with reference IDs, logging full errors internally' },
      { title: 'Sentry Integration', description: 'Full Sentry setup with request handlers, error tracking, and frontend error boundaries' },
      { title: 'Graceful Shutdown', description: 'Connection draining on SIGTERM with 30s timeout for zero-downtime deployments' },
      { title: 'Prisma Metrics', description: 'Database query tracking via Prometheus middleware for performance monitoring' },
      { title: 'Doc Consolidation', description: 'Moved old research docs to archive/, removed duplicates, cleaner project structure' },
    ],
  },
  {
    version: '1.0.7',
    date: '2026-01-17',
    type: 'security',
    title: 'Security Hardening',
    highlights: [
      'Fixed CVE-2023-45853 (zlib Integer Overflow) in Dockerfile with multi-stage build',
      'Path traversal prevention with new centralized security utilities',
      'Protected 10+ endpoints against path traversal attacks (CWE-23)',
      'Security event logging for blocked traversal attempts',
    ],
    features: [
      { title: 'Multi-stage Docker Build', description: 'Smaller attack surface with explicit security updates and build/runtime separation' },
      { title: 'Path Security Utils', description: 'New /server/utils/pathSecurity.js with isValidProjectName(), safePath(), validateAndResolvePath()' },
      { title: 'Protected Endpoints', description: 'Sessions, CLAUDE.md, settings, restart, delete, rename endpoints now validate paths' },
      { title: 'Route Protection', description: 'Files, logs, diff, and env routes now use path validation middleware' },
      { title: 'Security Logging', description: 'All blocked path traversal attempts logged with IP, path, and event type' },
    ],
  },
  {
    version: '1.0.6',
    date: '2026-01-17',
    type: 'major',
    title: 'Admin Dashboard Modularization',
    highlights: [
      'Refactored 5,544-line AdminDashboard.jsx into 35+ modular components',
      'New navigation: PROJECTS | SETTINGS | AUTOMATION | SERVER | SECURITY | HISTORY',
      'SETTINGS promoted to main tab (was nested 2 levels deep)',
      'New AUTOMATION tab combines AGENTS + MCP + SCHEDULED',
    ],
    features: [
      { title: 'Component Extraction', description: 'AdminDashboard reduced from 5,544 to 915 lines (83% reduction)' },
      { title: 'Tab Restructure', description: 'INFRASTRUCTURE renamed to SERVER, SETTINGS promoted, AUTOMATION created' },
      { title: 'Shared Components', description: 'New TabButton, SubTabBar, TabContainer, ErrorBoundary components' },
      { title: 'Error Boundaries', description: 'Each tab wrapped in error boundary for fault tolerance' },
      { title: 'API Endpoint Fixes', description: 'Fixed HistoryTab, ScheduledPane, Fail2banPane, ScanConfigPane endpoints' },
      { title: 'Organized Structure', description: 'New src/components/admin/ folder with tabs/, shared/, and constants' },
    ],
  },
  {
    version: '1.0.5',
    date: '2026-01-16',
    type: 'minor',
    title: 'Production Hardening & Observability',
    highlights: [
      'Added comprehensive security hardening with rate limiting and helmet headers',
      'Prometheus metrics export at /metrics endpoint for Grafana integration',
      'Backend testing infrastructure with 111 passing tests',
      'Zod validation schemas for all API endpoints',
    ],
    features: [
      { title: 'Security Headers', description: 'helmet middleware adds CSP, HSTS, X-Frame-Options, and other security headers' },
      { title: 'Rate Limiting', description: 'General (1000/15min), strict (10/min), and auth (10/15min) rate limiters protect all endpoints' },
      { title: 'Prometheus Metrics', description: 'HTTP duration histograms, request counters, WebSocket gauges, DB query metrics at /metrics' },
      { title: 'Slow Query Logging', description: 'Prisma queries exceeding 100ms are automatically logged with query details' },
      { title: 'Input Validation', description: '25+ Zod schemas validate all API input with detailed error messages' },
      { title: 'Backend Tests', description: '111 tests covering validation schemas, middleware, and metrics service' },
      { title: 'Watcher Alerts', description: 'PM2 watcher now integrates with AlertRule database for memory and service alerts' },
    ],
  },
  {
    version: '1.0.4',
    date: '2026-01-16',
    type: 'patch',
    title: 'Paste Fix & Structured Logging',
    highlights: [
      'Fixed double paste bug - content no longer duplicates when pasting',
      'Implemented structured pino logging throughout server codebase',
      'Replaced console.log/error/warn with JSON-formatted structured logs',
    ],
    features: [
      { title: 'Paste Deduplication', description: 'Added input deduplication to prevent paste events from firing twice within 100ms window' },
      { title: 'Structured Logging', description: 'Server now uses pino for JSON-formatted logs with context fields for better debugging' },
      { title: 'Log Categories', description: 'Separate loggers for server, session, socket, docker, and git operations' },
    ],
  },
  {
    version: '1.0.3',
    date: '2026-01-16',
    type: 'patch',
    title: 'Terminal Session Fixes & Project Management',
    highlights: [
      'Terminal buffer caching - scrollback preserved when switching sessions',
      'Fixed terminal reconnection showing blank screen on session switch',
      'Cloudflare widget now properly updates when selecting different projects',
      'Project tagging, priority, notes, and clone functionality',
      'Skip permissions toggle per-project for Claude sessions',
      'Enhanced context menu with multiple views and settings',
    ],
    features: [
      { title: 'Buffer Caching', description: 'Terminal scrollback is saved when switching projects and restored when returning' },
      { title: 'Session Reconnect', description: 'Fixed blank terminal on session switch with proper SIGWINCH refresh' },
      { title: 'Project Tags', description: 'Color-coded tags (Active, Archived, Infrastructure, Prototype, Production, WIP) with up to 3 visible in sidebar' },
      { title: 'Project Priority', description: 'Set High/Medium/Low priority with color indicators in context menu header' },
      { title: 'Project Notes', description: 'Add persistent notes to projects with title, content, pin to top, and delete' },
      { title: 'Clone Project', description: 'Duplicate any project with option to copy tags, notes, and settings (git history removed)' },
      { title: 'Skip Permissions', description: 'Per-project toggle to start Claude with --dangerously-skip-permissions flag' },
      { title: 'Cloudflare Widget', description: 'Fixed widget not updating when switching between projects' },
    ],
  },
  {
    version: '1.0.1',
    date: '2026-01-15',
    type: 'patch',
    title: 'Shpool Migration & Terminal Simplification',
    highlights: [
      'Migrated from tmux to shpool for lighter session persistence',
      'Removed custom right-click menu - browser default now works',
      'Native OSC 52 clipboard support (no special config needed)',
      'Simplified terminal codebase by removing 147 lines',
    ],
    features: [
      { title: 'Shpool Sessions', description: 'Replaced tmux with shpool for cleaner session persistence with raw byte passthrough' },
      { title: 'Session Naming', description: 'Changed session prefix from cp-* to sp-* for shpool sessions' },
      { title: 'Native Right-Click', description: 'Removed custom context menu - browser default now works natively' },
      { title: 'Auto-Reconnect', description: 'Sessions auto-create if none exists during reconnect' },
    ],
  },
  {
    version: '1.0.0',
    date: '2026-01-14',
    type: 'major',
    title: 'Console.web v1.0 - Complete Management Interface',
    highlights: [
      'Complete web-based management interface for Claude Code projects',
      'Browser-based terminals with session persistence - sessions survive disconnects',
      'Real-time system monitoring with 2-second CPU refresh across all cores',
      'Full infrastructure management: Docker, systemd, firewall, users, SSH',
      'AI automation with 13+ agents, MCP servers, and voice commands',
      'Comprehensive developer tools: API tester, database browser, Git workflow',
      'One-click system updates and first-time setup wizard',
      'GitHub integration with clone, push, and sync status',
      'Cloudflare Tunnels for one-click public deployment',
      'Widget-based customizable sidebars with drag-and-drop',
    ],
    features: [
      // Terminal & Sessions
      { title: 'Terminal Sessions', description: 'xterm.js terminals with session persistence, auto-reconnect, folders, tags, notes, templates, and team handoffs' },
      { title: 'Clipboard Support', description: 'Highlight-to-copy, Ctrl+Shift+C/V shortcuts, and OSC 52 integration' },
      { title: 'Session Sharing', description: 'Share sessions via links, add comments, activity feed, and team handoffs' },

      // Project Management
      { title: 'Project Browser', description: 'Browse projects with favorites, completion metrics, search, and CLAUDE.md editor' },
      { title: 'Project Templates', description: '6 template types: Full-Stack, Frontend, Desktop (Tauri), CLI, Infrastructure, Mobile (Flutter)' },
      { title: 'Compliance Checker', description: 'Weighted scoring for CI/CD, security, hooks, TypeScript strict, ESLint, Prettier, CLAUDE.md' },

      // System & Infrastructure
      { title: 'System Monitoring', description: 'Real-time CPU/memory/disk stats with delta-based CPU calculation' },
      { title: 'Docker Management', description: 'Full container lifecycle: start, stop, restart, logs, images, volumes' },
      { title: 'UFW Firewall', description: 'Enable/disable firewall, manage rules, quick actions for SSH/HTTP/HTTPS' },
      { title: 'Security Dashboard', description: 'Monitor SSH sessions, failed logins, fail2ban status, and security scanning' },

      // AI & Automation
      { title: 'Agent Marketplace', description: '13+ pre-built agents: ESLint, Prettier, Security Scanner, Test Runner, and more' },
      { title: 'MCP Server Catalog', description: '22+ MCP servers across 6 categories with one-click installation' },
      { title: 'Voice Commands', description: 'Browser-native speech recognition for voice commands in terminals' },

      // Integrations
      { title: 'Self-Update', description: 'One-click updates from Settings with real-time progress streaming' },
      { title: 'GitHub Integration', description: 'Clone repos, push changes, view sync status and workflow results' },
      { title: 'Cloudflare Tunnels', description: 'One-click publish with automatic DNS and route management' },

      // UI/UX
      { title: 'Setup Wizard', description: '5-step onboarding with feature selection, widget presets, and theme preview' },
      { title: 'Theme System', description: '11 glassmorphism themes with full CSS variable customization' },
      { title: 'Widget Dashboard', description: 'Drag-and-drop customizable widgets with vertical height snapping' },
    ],
  },
];
